version: '3'
services:
    web:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        env_file:
            - ./.env
        ports:
            - "5000:5000"

    postgres:
        container_name: postgres-cli_api
        restart: always
        build: ./docker/postgresql
        env_file:
            - ./.env
        volumes:
            - portfolio-site-db:/var/lib/postgresql/data
            - ./docker/postgresql/init_scripts:/docker-entrypoint-intdb.d
        ports:
            - "5432:5432"

volumes:
    portfolio-site-db:
