version: '3'
services:
    web:
        depends_on:
            - postgres
            - redis
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        volumes:
            - ./cli_api:/app/cli_api
            - ./tests:/app/tests
            # Allows launching of sibling containers
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - ./.env
        ports:
            - "5000:5000"

    postgres:
        container_name: postgres-cli_api
        restart: always
        build: ./docker/postgresql
        env_file:
            - ./.env
        volumes:
            - ./docker/postgresql/init_scripts:/docker-entrypoint-intdb.d
        ports:
            - "5432:5432"

    redis:
        env_file:
            - ./.env
        image: redis:latest
        restart: unless-stopped
        stop_grace_period: 3s
        ports:
            - "6379:6379"
